export const START_BROADCAST = 'START_BROADCAST'
export const START_BROADCAST_SUCCESS = 'START_BROADCAST_SUCCESS'
export const START_BROADCAST_FAILED = 'START_BROADCAST_FAILED'

export const STOP_BROADCAST = 'STOP_BROADCAST'
export const STOP_BROADCAST_SUCCESS = 'STOP_BROADCAST_SUCCESS'
export const STOP_BROADCAST_FAILED = 'STOP_BROADCAST_FAILED'
